site:
  title: Ceph Installation and Integration with RedHat OpenStack 18
  start_page: placeholder-course-name::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
