= Install packages

Run the below commands as `root` user on `cephservera`. 

NOTE: Installation process is time consuming task, consider running these steps in *tmux* session to avoid loss of connectivity during installation process.

. Register all your Ceph cluster nodes on Red Hat customer portal.
+
[source,bash,role=execute]
----
for server in cephservera cephserverb cephserverc cephserverd cephservere; do ssh $server subscription-manager register --username yourusername --password yourpassword;  done
----
+
Replace `yourusername` and `yourpassword` in the above command with appropriate string.
+
NOTE: You may not need to execute the above steps in the Red Hat training environment where a local packages repository is made available.

. Delete the local repository from all the servers if you are subscribing the system to RedHat customer portal.
+
[source,bash,role=execute]
----
for server in cephservera cephserverb cephserverc cephserverd cephservere; do ssh $server rm -f /etc/yum.repos.d/rhel*; done
----
+
NOTE: You may skip this step in Red Hat training environment where local packages repository is functional.

. Subscribe the cluster nodes to required RHEL9 and Ceph channels.
+
[source,bash,role=execute]
----
for server in cephservera cephserverb cephserverc cephserverd cephservere; do ssh $server subscription-manager repos --disable=* --enable=rhel-9-for-x86_64-baseos-rpms --enable=rhel-9-for-x86_64-appstream-rpms --enable=rhceph-7-tools-for-rhel-9-x86_64-rpms;  done
----

. Update all the Ceph cluster nodes to latest release.
+
[source,bash,role=execute]
----
for server in cephservera cephserverb cephserverc cephserverd cephservere; do ssh $server dnf -y update; done
----

. Install the packages required for Ceph storage deployment on all the cluster nodes.
+
[source,bash,role=execute]
----
for server in cephservera cephserverb cephserverc cephserverd cephservere; do ssh $server dnf -y install cephadm ceph-common lvm2 chrony podman; done
----

. Reboot the ceph server storage nodes.
+
Make sure the update and installation of packages is completed on all the nodes before rebooting.
+
[source,bash,role=execute]
----
for server in cephservere cephserverd cephserverc cephserverb cephservera; do ssh $server reboot; done
----

. After a couple of minutes, try connecting again to the ceph server nodes to make sure they are rebooted successfully.
+
[source,bash,role=execute]
----
for server in cephservere cephserverd cephserverc cephserverb cephservera; do ssh $server uptime; done
----
+
.Sample output
----
[student@utility ~]$ for server in cephservere cephserverd cephserverc cephserverb cephservera; do ssh $server uptime; done
 12:22:54 up 1 min,  0 users,  load average: 0.00, 0.00, 0.00
 12:22:54 up 1 min,  0 users,  load average: 0.21, 0.09, 0.03
 12:22:54 up 1 min,  0 users,  load average: 0.20, 0.07, 0.02
 12:22:54 up 1 min,  0 users,  load average: 0.03, 0.01, 0.00
 12:22:55 up 1 min,  0 users,  load average: 0.43, 0.09, 0.03
[student@utility ~]$ 
----
